// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.12.4
// source: pb/lottery.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LotteryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *LotteryRequest) Reset() {
	*x = LotteryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_lottery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LotteryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LotteryRequest) ProtoMessage() {}

func (x *LotteryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_lottery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LotteryRequest.ProtoReflect.Descriptor instead.
func (*LotteryRequest) Descriptor() ([]byte, []int) {
	return file_pb_lottery_proto_rawDescGZIP(), []int{0}
}

func (x *LotteryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LotteryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Win     bool   `protobuf:"varint,1,opt,name=win,proto3" json:"win,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LotteryResponse) Reset() {
	*x = LotteryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_lottery_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LotteryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LotteryResponse) ProtoMessage() {}

func (x *LotteryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_lottery_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LotteryResponse.ProtoReflect.Descriptor instead.
func (*LotteryResponse) Descriptor() ([]byte, []int) {
	return file_pb_lottery_proto_rawDescGZIP(), []int{1}
}

func (x *LotteryResponse) GetWin() bool {
	if x != nil {
		return x.Win
	}
	return false
}

func (x *LotteryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LotteryEntriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *LotteryEntriesRequest) Reset() {
	*x = LotteryEntriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_lottery_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LotteryEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LotteryEntriesRequest) ProtoMessage() {}

func (x *LotteryEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_lottery_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LotteryEntriesRequest.ProtoReflect.Descriptor instead.
func (*LotteryEntriesRequest) Descriptor() ([]byte, []int) {
	return file_pb_lottery_proto_rawDescGZIP(), []int{2}
}

func (x *LotteryEntriesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LotteryEntriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*LotteryResponse `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *LotteryEntriesResponse) Reset() {
	*x = LotteryEntriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_lottery_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LotteryEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LotteryEntriesResponse) ProtoMessage() {}

func (x *LotteryEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_lottery_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LotteryEntriesResponse.ProtoReflect.Descriptor instead.
func (*LotteryEntriesResponse) Descriptor() ([]byte, []int) {
	return file_pb_lottery_proto_rawDescGZIP(), []int{3}
}

func (x *LotteryEntriesResponse) GetEntries() []*LotteryResponse {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_pb_lottery_proto protoreflect.FileDescriptor

var file_pb_lottery_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x2f, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x22, 0x29, 0x0a, 0x0e, 0x4c,
	0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x0f, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x77, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x30, 0x0a, 0x15, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79,
	0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x16, 0x4c, 0x6f, 0x74, 0x74, 0x65,
	0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x32, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x4c, 0x6f, 0x74,
	0x74, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x07, 0x65, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x32, 0xa9, 0x01, 0x0a, 0x0e, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72,
	0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0c, 0x45, 0x6e, 0x74, 0x65,
	0x72, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x12, 0x17, 0x2e, 0x6c, 0x6f, 0x74, 0x74, 0x65,
	0x72, 0x79, 0x2e, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x4c, 0x6f, 0x74, 0x74,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x12, 0x1e, 0x2e, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x4c, 0x6f, 0x74, 0x74, 0x65,
	0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x4c, 0x6f, 0x74, 0x74, 0x65,
	0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x45, 0x66, 0x72, 0x69, 0x7a, 0x61, 0x6c, 0x2d, 0x6d, 0x2f, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72,
	0x79, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_lottery_proto_rawDescOnce sync.Once
	file_pb_lottery_proto_rawDescData = file_pb_lottery_proto_rawDesc
)

func file_pb_lottery_proto_rawDescGZIP() []byte {
	file_pb_lottery_proto_rawDescOnce.Do(func() {
		file_pb_lottery_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_lottery_proto_rawDescData)
	})
	return file_pb_lottery_proto_rawDescData
}

var file_pb_lottery_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_lottery_proto_goTypes = []interface{}{
	(*LotteryRequest)(nil),         // 0: lottery.LotteryRequest
	(*LotteryResponse)(nil),        // 1: lottery.LotteryResponse
	(*LotteryEntriesRequest)(nil),  // 2: lottery.LotteryEntriesRequest
	(*LotteryEntriesResponse)(nil), // 3: lottery.LotteryEntriesResponse
}
var file_pb_lottery_proto_depIdxs = []int32{
	1, // 0: lottery.LotteryEntriesResponse.entries:type_name -> lottery.LotteryResponse
	0, // 1: lottery.LotteryService.EnterLottery:input_type -> lottery.LotteryRequest
	2, // 2: lottery.LotteryService.GetLotteryEntries:input_type -> lottery.LotteryEntriesRequest
	1, // 3: lottery.LotteryService.EnterLottery:output_type -> lottery.LotteryResponse
	3, // 4: lottery.LotteryService.GetLotteryEntries:output_type -> lottery.LotteryEntriesResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_lottery_proto_init() }
func file_pb_lottery_proto_init() {
	if File_pb_lottery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_lottery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LotteryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_lottery_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LotteryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_lottery_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LotteryEntriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_lottery_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LotteryEntriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_lottery_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_lottery_proto_goTypes,
		DependencyIndexes: file_pb_lottery_proto_depIdxs,
		MessageInfos:      file_pb_lottery_proto_msgTypes,
	}.Build()
	File_pb_lottery_proto = out.File
	file_pb_lottery_proto_rawDesc = nil
	file_pb_lottery_proto_goTypes = nil
	file_pb_lottery_proto_depIdxs = nil
}
